PROJ = disp_rx

PIN_DEF = feather.pcf
DEVICE = up5k

SRC_PATH = ../common/
ADD_SRC = \
		$(SRC_PATH)clk_div_hz.v \
		$(SRC_PATH)led_matrix.v \
		$(SRC_PATH)uart_rx.v \
		$(SRC_PATH)char_disp.v

include ../common.mk
