PROJ = disp_tx

PIN_DEF = feather.pcf
DEVICE = up5k

SRC_PATH = ../common/
ADD_SRC = \
		$(SRC_PATH)led_matrix.v \
		$(SRC_PATH)uart_tx.v \
		$(SRC_PATH)char_disp.v \
		$(SRC_PATH)clk_div_hz.v \
		$(SRC_PATH)debounce.v

include ../common.mk
